name: Rmap
dependencies:
  - numpy
  - pandas
  - pandas-datareader
  - xlrd >= 1.0.0
  - pycountry
  - plotly
  - dash
  - folium
  - geopy
  - matplotlib
  - pystan
  - r-data.table
  - r-envstats
  - r-rstan
  - r-ggplot2
  - r-geosphere
  - r-optparse
  - r-BH
channels:
  - conda-forge
