name: Rmap
dependencies:
  - pandas
  - openpyxl
  - r-base
  - r-essentials
  - r-data.table
  - r-rstan
  - r-rjson
  - r-StanHeaders
  - r-envstats
  - r-ggplot2
  - r-geosphere
  - r-optparse
  - r-codetools
  - r-gsubfn
  - r-plyr
  - r-BH
channels:
  - conda-forge
