name: Rmap-daily-update
dependencies:
  - pandas
  - numpy
  - scipy
  - lxml
  - requests
  - xlrd
  - openpyxl
  - matplotlib
  - r-base
  - r-essentials
  - r-data.table
  - r-rstan
  - r-rjson
  - r-StanHeaders
  - r-envstats
  - r-ggplot2
  - r-geosphere
  - r-optparse
  - r-codetools
  - r-gsubfn
  - r-plyr
  - r-BH
  - pip
  - pip:
    - geopy
    - git+git://github.com/epimap/covid19_datasets.git@master
channels:
  - conda-forge
