name: Rmap
dependencies:
  - numpy
  - pandas
  - pandas-datareader
  - xlrd >= 1.0.0
  - pycountry
  - plotly
  - dash
  - folium
  - r-data.table
  - r-envstats
  - r-rstan
  - r-ggplot2
channels:
  - conda-forge
