name: Rmap
dependencies:
  - numpy
  - pandas
  - pandas-datareader
  - xlrd >= 1.0.0
  - pycountry
  - openpyxl
  - plotly
  - geopy
  - matplotlib
  - r-base
  - r-essentials
  - r-data.table
  - r-envstats
  - r-ggplot2
  - r-geosphere
  - r-optparse
  - r-codetools
  - r-BH
  - r-StanHeaders
  - r-rstan
channels:
  - conda-forge
